CHANGELOG.md, Introspect.xcodeproj/project.pbxproj, Introspect.xcodeproj/xcuserdata/ldiqual.xcuserdatad/xcschemes/xcschememanagement.plist, Introspect/AppKitIntrospectionView.swift, Introspect/ViewExtensions.swift, IntrospectTests/AppKitTests.swift
From https://github.com/siteline/SwiftUI-Introspect/pull/15
Additions from original PR:
- Test support
- Changelog
=> Enable Catalyst support for iOS framework

Introspect/AppKitIntrospectionView.swift, Introspect/UIKitIntrospectionView.swift, Introspect/UIKitIntrospectionViewController.swift, Introspect/ViewExtensions.swift, IntrospectTests/AppKitTests.swift, IntrospectTests/UIKitTests.swift
=> Resolve malformed macOS version @available directives causing issues on Big Sur

.circleci/config.yml, CHANGELOG.md
We need to upgrade to Xcode 12.4.0 for macOS 11 SDK support.
This is needed in order to get #52 merged.
=> Use Xcode 12.4.0 on CircleCI

.github/workflows/build-and-test.yml, CHANGELOG.md, IntrospectTests/AppKitTests.swift, IntrospectTests/UIKitTests.swift
This PR adds a Github Workflow which triggers on `push` and `pull_request`.
The workflow is modeled very closely after the existing CircleCI workflow.
Merging this will improve the general QA workflow a lot, since pull requests from forks will be testable without creating a separate branch.
There is no action limit for public repositories.
=> Add GitHub action

CHANGELOG.md, Introspect/ViewExtensions.swift, IntrospectTests/AppKitTests.swift
This adds a method to introspect a `SwiftUI.TabView` and retrieve the corresponding `NSTabView`.
It thereby fixes #32.
=> Add introspection for `NSTabView`

CHANGELOG.md, Introspect/ViewExtensions.swift, IntrospectTests/AppKitTests.swift, IntrospectTests/UIKitTests.swift
This PR adds color well introspection to iOS and macOS, thereby resolving #59.
=> Add .introspectColorWell()

CHANGELOG.md, Introspect/Introspect.swift, Introspect/ViewExtensions.swift, IntrospectTests/UIKitTests.swift, fastlane/Fastfile
This adds introspection of the UISplitViewController on iOS and thereby fixes #70.
=> Add .introspectSplitViewController() on iOS

README.md
This adds the `findChildUsingFrame` function to the README.md thereby resolving #90.
=> Add findChildUsingFrame to README

Introspect/ViewExtensions.swift
Since Swift 5.1, [SE-0255](https://github.com/apple/swift-evolution/blob/master/proposals/0255-omit-return.md) evolved Swift to have the capability to implicitly return from functions.
I removed unnecessary explicit returns to improve code readability and simplicity.
=> Remove explicit returns to simplify code

README.md
[Cocoapods](https://guides.cocoapods.org/syntax/podfile.html) syntax follows the syntax to use single quotes to add Pods to a Podfile. Though it is implicit, many users will copy the method provided in the readme and face issues due to the double quotes used.
Hence the only change in this pull request is changing`pod "Introspect"` to  `pod 'Introspect'`.
=> fix: update Cocoapods install statement

Introspect/UIKitIntrospectionView.swift
I ran into the issue described in #140 and the fix described worked for me. We are using `introspectScrollView` within a `LazyVStack` and without this fix introspect fails when the scrollview is "below the fold". In our case we have nested ScrollViews something like this:
```swift
ScrollView(.vertical) {
LazyVStack {
ScrollView(.horizontal) {
}
.introspectScrollView {
// This fails when the horizontal scrollview is below the fold.
}
}
}
```
=> Fix issue where introspecting within a LazyVStack would silently fail

Introspect/UIKitIntrospectionView.swift, Introspect/UIKitIntrospectionViewController.swift
This actually fixes the regression in #194. My bad for not checking better. A good area of improvement for automated tests.
=> Hotfix 0.2.1

Introspect/ViewExtensions.swift, IntrospectTests/UIKitTests.swift
The paged Tab View should be handled differently on iOS 16, today we must handle this on the call site, wrapping our views in a `if #available(iOS 16, *)` .
I suggest we handle this directly in the library, on the `introspectPagedTabView` method.
=> Fix `introspectPagedTabView` on iOS 16

CHANGELOG.md, Package.swift
This unlocks some newer language features required for the upcoming new API in #207.
Thankfully there aren't many more sizeable benefits for this library in Swift 5.6 onwards, so we'll easily be able to support Swift 5.5 for quite along time as part of the 1.0 semver contract.
=> Bump minimum Swift version to 5.5

README.md
This PR updates the README to include the newly added `introspectCollectionView()` and `introspectCollectionViewCell()` functions from PR #169. It also clarifies that these new functions are available for Lists on iOS 16 and above, while the `introspectTableView()` and `introspectTableViewCell()` functions are available for iOS 15 and below.
```
- Added `introspectCollectionView()` and `introspectCollectionViewCell()` functions to the README
- Clarified that the new functions are available for Lists on iOS 16 and above
- Specified that `introspectTableView()` and `introspectTableViewCell()` are available for iOS 15 and below
```
Please let me know if any changes or additional information are required. Thank you!
=> Update README to include UICollectionView introspection support

Introspect/Introspect.swift, Introspect/ViewExtensions.swift, IntrospectTests/AppKitTests.swift, IntrospectTests/UIKitTests.swift
This should fix issue:
[issues 162](https://github.com/siteline/SwiftUI-Introspect/issues/162)
Fixes:
```swift
struct ContentView: View {
var body: some View {
HStack {
ScrollViewReader { proxy in
ScrollView(.horizontal) {
TimeLineView()
}
.introspectScrollView { scrollView in
print(scrollView)    //closure not called when clipped or masked
}
.clipped()              // this caused issues
.mask(Text("Hello"))    // or this
.clipShape(Rectangle()) // and this
}
}
}
}
```
=> Fix finding UIScrollViews that are clipped(), masked or combined with clipShape() or cornerRadius()

Sources/Introspect.swift, Sources/IntrospectionView.swift, Sources/PlatformView.swift, Sources/Voodoo.swift
This took some heavy generics voodoo, but it seems to work quite nicely.
=> Unify `introspect` modifiers

Sources/ViewTypes/VideoPlayer.swift, Tests/Tests.xcodeproj/project.pbxproj, Tests/Tests/ViewTypes/VideoPlayerTests.swift, docs/SwiftUIIntrospect.md
=> Add `VideoPlayer` introspection

CHANGELOG.md, Examples/Showcase/Showcase.xcodeproj/project.pbxproj, Examples/Showcase/Showcase/App.swift, Examples/Showcase/Showcase/AppView.swift, Sources/Introspect.swift, Sources/ViewTypes/Window.swift, Tests/Tests.xcodeproj/project.pbxproj, Tests/Tests/ViewTypes/WindowTests.swift, docs/SwiftUIIntrospect.md
=> Add window introspection

CHANGELOG.md, Sources/Introspect.swift, Sources/IntrospectionSelector.swift, Sources/PlatformVersion.swift, Sources/PlatformViewVersion.swift, Tests/Tests.xcodeproj/project.pbxproj, Tests/Tests/PlatformTests.swift, Tests/Tests/PlatformVersionTests.swift
This is a different take on #284 without overloading the `introspect` modifier, as suggested by @paescebu.
It reads quite clean, though it's a tiny bit more obscure to find (which might be a good thing, really), and it allows mixing current + current and past matching all in the same expression (which again, might be a good thing).
Examples:
```swift
import SwiftUI
@_spi(Advanced) import SwiftUIIntrospect
struct ContentView: View {
@State var name = ""
var body: some View {
TextField("Name", text: $name)
.introspect(.textField, on: .iOS(.v13...)) { textField in
// do something with textField
}
}
}
```
```swift
struct ContentView: View {
var body: some View {
List {
Text("Item 1")
Text("Item 2")
}
.introspect(.list, on: .iOS(.v13, .v14, .v15)) { tableView in
}
.introspect(.list, on: …
```
=> Add advanced range-based platform version predicates

CHANGELOG.md, Sources/Introspect.swift
Fixes #304.
Whilst this isn't the most elegant fix, it works. I guess my only reservation with it is that it introduces an ad-hoc piece of logic that can't be replicated outside the core library, but we can probably live with this very narrow edge case.
=> Only box up content for `.view` introspection

CHANGELOG.md, README.md, Sources/ViewTypes/SecureField.swift, Tests/Tests.xcodeproj/project.pbxproj, Tests/Tests/ViewTypes/SecureFieldTests.swift
Same as `TextField`, but good to have the specific view type to help intuitiveness.
Originates in #316.
=> Add `SecureField` introspection

.github/workflows/ci.yml
Just improving maintainability of our decently complex GitHub Actions manifest.
=> [CI] Make macOS and Xcode versions explicit

CHANGELOG.md, Examples/Showcase/Showcase/AppView.swift, Sources/ViewTypes/Toggle.swift, Sources/ViewTypes/ToggleWithSwitchStyle.swift, Tests/Tests/TestUtils.swift, Tests/Tests/ViewTypes/ToggleTests.swift, Tests/Tests/ViewTypes/ToggleWithSwitchStyleTests.swift
visionOS 1.0 beta 4 changed the underlying `Toggle` implementation and is no longer backed by a UIKit view, so sadly we'll need to remove this.
As visionOS 1.0 is still technically considered beta I don't consider this worthy of a major library version bump, so next version will simply be 1.1.0.
=> Remove `Toggle` introspection on visionOS

Sources/PlatformVersion.swift
Fixes "Protocol requirement ... cannot be declared '@_spi' ..." error 
that happens with compile flag BUILD_LIBRARY_FOR_DISTRIBUTION=YES
This issue was reported and fixed once before but reappears after the latest code changes
https://github.com/siteline/swiftui-introspect/issues/336
Applied same fix as in https://github.com/siteline/swiftui-introspect/pull/339
=> Fix "Protocol requirement cannot be declared '@_spi'"

.github/workflows/ci.yml, SwiftUIIntrospect.xcworkspace/xcshareddata/swiftpm/Package.resolved, Tests/Tests.xcodeproj/project.pbxproj, fastlane/Fastfile
Fixes #406. This also requires disabling UI tests but oh well.
=> Remove SimulatorStatusMagic

.github/workflows/cd.yml, script/pod_release
Tired of the CocoaPods key expiring and not being able to change it as I don't have the required permissions so I'm just switching to manual releases.
=> Infra: disable CD and add manual CocoaPods release script

Sources/Introspect.swift, Sources/IntrospectionView.swift
Something in the way SwiftUI works in xOS 26 makes it so that some views aren't quite ready to be customized by the time they're handed over via the `customize` closure. In this instance, a thread hop is necessary. While we already had a similar mechanism for some iOS 13 scenarios, they were guarded behind `#available`, but now that it's more generalized it makes sense to do it always. I've added a disclaimer to `.introspect` explaining this caveat.
Fixes #465.
=> Thread hop to ensure 2026 platform compatibility

Sources/ViewTypes/Button.swift, Sources/ViewTypes/ToggleWithButtonStyle.swift, Tests/Tests/ViewTypes/ButtonTests.swift, Tests/Tests/ViewTypes/ToggleWithButtonStyleTests.swift
I just installed macOS 26 and there seems to be a couple things no longer introspectable on macOS 26 so here's the PR to reflect that before tagging the official v26 release.
=> Mark unavailable macOS 26 introspections
